### ISSUE TITLE
easing - is there a list of buildin functions?

### ISSUE THREAD

**Issue by s-light** [Eartz/animatePaper.js#10]
I would like to know what easing functions are build in - and what they do -
is there some comparsion at som point available or a simple text list of possible values for build in functions?
from the examples i found
- `easeInElastic`
- `easeInBounce`
- `swing`
and the [part that says how to add own functions ](https://github.com/Eartz/animatePaper.js#add-custom-easing-functions)

additionally in the [source of easing.js](https://github.com/Eartz/animatePaper.js/blob/master/src/easing.js) there seems to be a bunch of additional variants - 
- `linear`
- `swing`
- `Sine`
- `Circ`
- `Elastic`
- `Back`
- `Bounce`
and
- `Quad`
- `Cubic`
- `Quart`
- `Quint`
- `Expo`
for this some of the names makes some sense to me - but i don't know the math behind these things..
after this there seems to be some 'combined' ones but i don't understand how this works or what they do... :-?
- `easeIn` + name
- `easeOut` + name
- `easeInOut` + name

can you give some hints on this please :-)

**Comment by s-light** [comment]
ok digged some deeper and found
http://upshots.org/actionscript/jsas-understanding-easing
the first paragraph is a good overview  - i think i have some ideas now..

**Comment by camille-hdl** [comment]
Hi,

[this link](http://easings.net/en) explains things visually. The "easeIn", "easeOut" and "easeInOut" prefixes indicate if the "effect" happens at the beginning of the animation, at the end, or both respectively.

I merely used existing implementations so I'm not going to pretend I can explain the math behind the more complex functions (e.g. Elastic), but as far as Expo, Sine, Cubic, ... go, they are the same functions you would find on your scientific calculator.

Hope this helps !

**Comment by s-light** [comment]
Hi Eartz,
thanks for your reply,
great link/explanation. i think i have understand it now :-)
eventually a list + the link in the documentation / Guide page would be a good help for new users :-)

sunny greetings stefan

**Comment by camille-hdl** [comment]
I'd love to improve the doc / readme and it will be done eventually but if you have ideas such as this one, just do a pull request and I'll happily integrate your changes 👍 

cheers
