### ISSUE TITLE
[question] Why is it not possible to animate Group fillColor?

### ISSUE THREAD

**Issue by s-light** [Eartz/animatePaper.js#11]
as the title asks - Why is it not possible to animate the `fillColor` of a Group?
this is a 'mandatory' feature to be able to work with imported svg files - as they are heavily structured with groups...

i understand that i have to fist define the fillColor of the group so it can be animated. but i have done this as in 

```js
    const group_active = new paper.Group([
            group_sub,
            step0_layer.children.Gx,
        ]);
        group_active.name = "group_active";
        step0_layer.addChild(group_active);
        // define fillColor
        group_active.fillColor = {
            red: 0.6,
            green: 0.7,
            blue: 0.7,
        };
        const ani_item = group_active;
        animatePaper.stop(ani_item);
        animatePaper.animate(ani_item, [
            {
                properties: {
                    fillColor: {
                        red: 0.9,
                        green: 0.1,
                        blue: 0.1,
                    },
                },
                settings: {
                    duration: 500,
                    easing: "swing",
                    complete: () => {
                        console.log("done :-)");
                    }
                }
            }
        ]);
```
and if i try it i get a `TypeError: tween.item[tween.prop] is undefined` in `_tweenPropHooks.Color.set`

would it be possible to add this with the [Extend property hooks](https://github.com/Eartz/animatePaper.js#extend-property-hooks) option? 
is there somewhere an concrete example on how to implement a new hook?
the documentation is missing an example how to actual implement the set / get / ease functions..
but i will try and experiment with it... hope this works ;-)

sunny greetings stefan

**Comment by s-light** [comment]
have digged some deeper.
seems to be multiple problems.
1. the current Color animation concept does not account for rgb type..
2. the paper color class seems to be a little buggy with setting single properties to new values or/and in general there is a bug if you try to set a item.fillColor with a instance of the paper.Color class. 
this worked for me:
```
                set: function(tween) {
                    // console.log("set", tween);
                    // console.log("tween.item", tween.item);
                    // console.log("tween.item.fillColor", tween.item.fillColor);

                    if (typeof tween.end.lightness !== "undefined") {
                        // console.log("tween.item.fillColor", tween.item.fillColor);
                        const fc = tween.item.fillColor;
                        const color_new = {
                            hue: fc.hue + tween.now.hue,
                            lightness: fc.lightness + tween.now.lightness,
                            saturation: fc.saturation + tween.now.saturation,
                        };
                        tween.item.fillColor = color_new;
                    } else {
                        const fc = tween.item.fillColor;
                        const color_new = {
                            hue: fc.hue + tween.now.hue,
                            brightness: fc.brightness + tween.now.brightness,
                            saturation: fc.saturation + tween.now.saturation,
                        };
                        tween.item.fillColor = color_new;
                    }
                },
```
have not tried any more. (iam running out of time for the current project - so have to doe some more test later)

i also had a short try at implementing the rgb handling have a look at https://github.com/s-light/animatePaper.js/tree/ColorRGB-support
but currently it does not work. (error: Color._type properties is not define...)

**Comment by s-light** [comment]
just a short update - i think i will have time to  write a 'temporary workaround' for other color types and group capability next week and than can make pull request. i will let you know here if/when i start on this.

**Comment by camille-hdl** [comment]
Hi,

that would be great ! Thank you

cheers

**Comment by s-light** [comment]
have added a pull request #12 :-)
