### ISSUE TITLE
why is 0 as duration not allowed? [question]

### ISSUE THREAD

**Issue by s-light** [Eartz/animatePaper.js#17]
Is there a technical reason to only allow `settings.duration`values >= 1?
its explicitly checked for in [animation.js#L268](https://github.com/Eartz/animatePaper.js/blob/dce9c08cd7e84e2d7ead7469548ae107ee7daf55/src/animation.js#L268)
for some of my animation sequences i would like to use duration: 0 to make hard jumps. and sometimes it seams to me that the duration:1 is visible..

**Comment by camille-hdl** [comment]
In hindsight it looks weird to me too, according to the comment it should only check for values < 0,
I'll fix that !

cheers
