### ISSUE TITLE
Rotate animation only works once

### ISSUE THREAD

**Issue by StratusBase** [Eartz/animatePaper.js#6]
When using the "rotate" property, I noticed that it can only be fired one time and subsequent rotation animations would never actually rotate (if re-using the same rotation angle). When logging the target object's data._animatePaperVals.rotate value, it would always properly adjust during the first animation. After that, it would always be the value that the property was set to.

A fix that I came up with (which is just a hack) is to use the complete callback and set the target object's data._animatePaperVals.rotate value to 0. This would allow subsequent animations to rotate properly.

`
 target.animate({
          properties: {
            rotate: 360
          },
          settings: {
            duration: 1000,
            easing:"linear",
            step: function(percent) {
              console.log(percent, target.data._animatePaperVals.rotate);
              updateBoundingBox();
            },
            complete: function() {
              target.data._animatePaperVals.rotate = 0;
              console.log(target.data._animatePaperVals.rotate);
            }
          }
        });
`

**Comment by camille-hdl** [comment]
So when I told you I'd look into this in the coming days (that was 23 days ago) I might have overestimated my free time, sorry about that.

In this code, you are using an absolute value `360` but If I'm guessing right you should be using a relative value `'+360'`.   
If you are using an absolute value, the first animation will aim to finish at 360°, so if you animate it again with the same value it won't move (as intended). If you use a relative value however, it will aim for currentRotation+360.

Does this solve your problem ?

**Comment by StratusBase** [comment]
If I set the value to a relative one it still stops after the first rotation. I believe this is how I originally found the issue because I tried absolute and relative values with the same result...


     
    animate.rotate = function(target, loop) {

      animatePaper.animate(target, [{
        properties: {
          rotate: '+360'
        },
        settings: {
          referencePoint: target.center,
          duration: 2000,
          easing:"linear",
          step: function(percent) {
            //console.log(percent, target.data._animatePaperVals.rotate);
          },
          complete: function() {

            // Hack to fix rotation issues
            // target.data._animatePaperVals.rotate = 0;

            // Loop
            if (!loop) return;

            // Loop
            animate.rotate(target, loop);
          }
        }
      }]);
    };

**Comment by camille-hdl** [comment]
I think I see the problem, can you try with the current build on master ? (using relative values)

**Comment by StratusBase** [comment]
Much better! Thank you!
