### ISSUE TITLE
Animate "rotate" with reference point

### ISSUE THREAD

**Issue by StratusBase** [Eartz/animatePaper.js#7]
This is more of a suggestion rather than an issue. I saw in your tween.js source file that you're looking for a way to add parameters to the rotate animation. I extended the property hook with the following to get the desired result by adding a referencePoint value in the animation's settings property.

Here's my code:

```
  // Override rotate hook to support a reference point in animations
  animatePaper.extendPropHooks({
    rotate: {
        get: function(tween) {
            if (!tween.item.data._animatePaperVals) {
                tween.item.data._animatePaperVals = {};
            }
            if (typeof tween.item.data._animatePaperVals.rotate === "undefined") {
                tween.item.data._animatePaperVals.rotate = -0;
            }
            var output = tween.item.data._animatePaperVals.rotate;
            return output;
        },
        set: function(tween) {
            var curRotate = tween.item.data._animatePaperVals.rotate;
            var trueRotate = tween.now - curRotate;
            tween.item.data._animatePaperVals.rotate = tween.now;
            if (typeof tween.A.settings.referencePoint === "underfined") {
              tween.item.rotate(trueRotate);
            } else {
              tween.item.rotate(trueRotate, tween.A.settings.referencePoint);
            }
        }
    }});
```

And here's my example of the "revolve" animation with the specified referencePoint value:

```
revolve: function(target, referencePoint, loop) {
      target.animate([{
        properties: {
          rotate: 360
        },
        settings: {
          referencePoint: referencePoint,
          duration: 5000,
          easing: "linear",
          step: function(percent) {
            //console.log(percent, target.data._animatePaperVals.rotate);
            updateBoundingBox();
          },
          complete: function() {
            // Hack to fix rotation issues
            target.data._animatePaperVals.rotate = 0;
            if (!loop) return;
            ANIMATE.revolve(target, referencePoint, loop);
          }
        }
      }]); }
```

(Eartz: edited for styling)

**Comment by camille-hdl** [comment]
Hi, thank you for your suggestions and improvements !

I'll look into it soonish when I have enough time to do it properly (maybe before the end of the week but if i'm realistic it will probably be in two weeks).

I'll probably take care of the bug you reported in the other issue first though.

cheers

**Comment by StratusBase** [comment]
Awesome, that sounds great.

I will continue to submit issues / requests if I find anything else as I
will be using this heavily.

Thank you,

Steven

**Comment by camille-hdl** [comment]
Hi,
it took a bit longer than expected but I finally took the time to sit down and work on things, so v1.0.1 is here.

I used your example but used the word `center` instead of `referencePoint` to be more consistent with the paper.js doc.
You can use `settings.center` to provide the `center` argument (an instance of `paper.Point`) to `rotate` and `scale`. If you want to change both properties with different centers, use `rotateCenter` and `scaleCenter` instead.

Thank you again for your help

I'm closing this issue, but I'll be happy to read your feedback here or in new Issues if you encounter any problem !
