### ISSUE TITLE
animate position strange behavior

### ISSUE THREAD

**Issue by s-light** [Eartz/animatePaper.js#8]
i tried to use the position animation.
based on the example given in the documentation.
changed to use absolute values - idea is that the box slideds to the position where you clicked with your mouse-cursor.
but the box does only the y property - the x is set to the same value as the y. so it slieds from the top left down-right in 45° up to the height where you click. that seems strange..
i have uploaded my example at
[animation_simple.html](https://github.com/s-light/paper.js_tests/blob/c0f412b4ad31f8d0cb855de8c12eb25f9a7f138b/animation_simple.html)
[/js/animation_simple..js](https://github.com/s-light/paper.js_tests/blob/c0f412b4ad31f8d0cb855de8c12eb25f9a7f138b/js/animation_simple.js)

basically i do the following:
```
    moveToPosition(event) {
        const position_new = new paper.Point(event.clientX, event.clientY);
        this.rect0.animate({
            properties: {
                position: position_new
            },
            settings: {
                duration: 500,
                easing: "swing"
            }
        });
    }
```
i also tried with
```
   moveToPosition(event) {
        this.rect0.animate({
            properties: {
                position: {
                    x: event.clientX,
                    y: event.clientY,
                }
            },
            settings: {
                duration: 500,
                easing: "swing"
            }
        });
    }
```
both had the same behavior.

is this a bug or have i missed something/didn't understand the concept?

**Comment by s-light** [comment]
have tested some more:
if i use this example
```
var square = new paper.Path.Rectangle(new paper.Point(75, 75), new paper.Size(50,50));
square.strokeColor = 'green';
square.animate({
  properties: {
    position: {
      x: "+500", // relative to the current position of the item. At the end, `x` will be : 275
      y: 150     // absolute position. At the end, `y` will be : 150
    },
    strokeColor: {
      hue: "+100",
      brightness: "-0.4"
    }
  },
  settings: {
    duration:1500,
    easing:"easeInBounce"
  }
})
``` 
and change the `x: "+500", ` to ` x: 500, ` it stops working correctly. so it seems that there is a bug if both values are absolute.
on the first look at [prophooks.js L151](https://github.com/Eartz/animatePaper.js/blob/master/src/prophooks.js#L151) i did not notice something that seems off. but i don't know if the bug is coursed by this part of the code...

**Comment by camille-hdl** [comment]
Hi,

thank you for reporting this, I will look into into it as soon as I have the time !  
The links to your examples seem to 404 though, maybe your repo is private ?

cheers

**Comment by camille-hdl** [comment]
Also, an idea:

in your demo in #9 you are using a build from bower so I assume you're using it here as well. 

Since the last tagged release I made a few changes and fixes so you may want to try using one of the builds in master in the dist/ directory and see if you still see this bug.

**Comment by s-light** [comment]
Hi Eartz,
thanks for your great library!
i have updated the links - i renamed the files and did not use permanent links..
edit: assumption correct i am using the bower version. i will try the git:master variant.
sunny greetings stefan

**Comment by s-light** [comment]
Hi Eartz,
i have cloned the master branch and linked this locally - that did fix this issue. 
thanks for your great library!
by the way: as fare as i can tell it also works with [yarn](https://yarnpkg.com/) in combination with [webpack](https://webpack.js.org/) (i have just started to use these tools...)

**Comment by camille-hdl** [comment]
Hi !

I'm glad your problem is fixed, I haven't found the time to do another release yet but I'm still hoping to do that Soon(tm).

Also thanks for the information about yarn and webpack 👍

cheers
